/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.1601)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2017
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/
USE [master]
GO
/****** Object:  Database [Twitter_db]    Script Date: 09-Feb-18 2:57:16 PM ******/
CREATE DATABASE [Twitter_db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Twitter_db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Twitter_db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Twitter_db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Twitter_db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Twitter_db] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Twitter_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Twitter_db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Twitter_db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Twitter_db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Twitter_db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Twitter_db] SET ARITHABORT OFF 
GO
ALTER DATABASE [Twitter_db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Twitter_db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Twitter_db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Twitter_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Twitter_db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Twitter_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Twitter_db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Twitter_db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Twitter_db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Twitter_db] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Twitter_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Twitter_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Twitter_db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Twitter_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Twitter_db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Twitter_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Twitter_db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Twitter_db] SET RECOVERY FULL 
GO
ALTER DATABASE [Twitter_db] SET  MULTI_USER 
GO
ALTER DATABASE [Twitter_db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Twitter_db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Twitter_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Twitter_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Twitter_db] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Twitter_db', N'ON'
GO
ALTER DATABASE [Twitter_db] SET QUERY_STORE = OFF
GO
USE [Twitter_db]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Twitter_db]
GO
/****** Object:  User [twitterDbUser]    Script Date: 09-Feb-18 2:57:16 PM ******/
CREATE USER [twitterDbUser] FOR LOGIN [twitterDbUser] WITH DEFAULT_SCHEMA=[db_accessadmin]
GO
/****** Object:  Table [dbo].[Followers]    Script Date: 09-Feb-18 2:57:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Followers](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[follower_id] [int] NOT NULL,
 CONSTRAINT [PK_Followers] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[sysdiagrams]    Script Date: 09-Feb-18 2:57:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[sysdiagrams](
	[name] [nvarchar](128) NOT NULL,
	[principal_id] [int] NOT NULL,
	[diagram_id] [int] IDENTITY(1,1) NOT NULL,
	[version] [int] NULL,
	[definition] [varbinary](max) NULL,
 CONSTRAINT [PK_sysdiagrams] PRIMARY KEY CLUSTERED 
(
	[diagram_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tweets]    Script Date: 09-Feb-18 2:57:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tweets](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[user_id] [int] NOT NULL,
	[text] [varchar](140) NOT NULL,
	[post_date] [datetime] NOT NULL,
 CONSTRAINT [PK_Tweets] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 09-Feb-18 2:57:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[email] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[firstname] [varchar](50) NOT NULL,
	[lastname] [varchar](50) NOT NULL,
	[avatar] [varchar](200) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_follower_ID]    Script Date: 09-Feb-18 2:57:16 PM ******/
CREATE NONCLUSTERED INDEX [IX_FK_follower_ID] ON [dbo].[Followers]
(
	[follower_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_Follower_user_ID]    Script Date: 09-Feb-18 2:57:16 PM ******/
CREATE NONCLUSTERED INDEX [IX_FK_Follower_user_ID] ON [dbo].[Followers]
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_FK_user_ID]    Script Date: 09-Feb-18 2:57:16 PM ******/
CREATE NONCLUSTERED INDEX [IX_FK_user_ID] ON [dbo].[Tweets]
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Followers]  WITH CHECK ADD  CONSTRAINT [FK_follower_ID] FOREIGN KEY([follower_id])
REFERENCES [dbo].[Users] ([id])
GO
ALTER TABLE [dbo].[Followers] CHECK CONSTRAINT [FK_follower_ID]
GO
ALTER TABLE [dbo].[Followers]  WITH CHECK ADD  CONSTRAINT [FK_Follower_user_ID] FOREIGN KEY([user_id])
REFERENCES [dbo].[Users] ([id])
GO
ALTER TABLE [dbo].[Followers] CHECK CONSTRAINT [FK_Follower_user_ID]
GO
ALTER TABLE [dbo].[Tweets]  WITH CHECK ADD  CONSTRAINT [FK_user_ID] FOREIGN KEY([user_id])
REFERENCES [dbo].[Users] ([id])
GO
ALTER TABLE [dbo].[Tweets] CHECK CONSTRAINT [FK_user_ID]
GO
/****** Object:  StoredProcedure [dbo].[USP_FOLLOW]    Script Date: 09-Feb-18 2:57:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_FOLLOW]
	@userId int,
	@followerId int
AS
BEGIN
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	INSERT INTO [dbo].[Followers] ([user_id], [follower_id])
	VALUES (@userId, @followerId)
END
GO
/****** Object:  StoredProcedure [dbo].[USP_GET_ALL_USERS]    Script Date: 09-Feb-18 2:57:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_GET_ALL_USERS]
AS
BEGIN
	SET NOCOUNT ON;
	SELECT [ID], [USERNAME], [EMAIL], [FIRSTNAME], [LASTNAME], [AVATAR] FROM [Users]
END
GO
/****** Object:  StoredProcedure [dbo].[USP_GET_USER_BY_EMAIL]    Script Date: 09-Feb-18 2:57:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_GET_USER_BY_EMAIL]
	@email VARCHAR(100)
AS
BEGIN
	SET NOCOUNT ON;
	SELECT [ID], [USERNAME], [EMAIL], [FIRSTNAME], [LASTNAME], [AVATAR] FROM [Users]
	WHERE email = @email
END
GO
/****** Object:  StoredProcedure [dbo].[USP_GET_USER_BY_ID]    Script Date: 09-Feb-18 2:57:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_GET_USER_BY_ID]
	@userId int
AS
BEGIN
	SET NOCOUNT ON;
	SELECT [ID], [USERNAME], [EMAIL], [FIRSTNAME], [LASTNAME], [AVATAR] FROM [Users]
	WHERE id = @userId
END
GO
USE [master]
GO
ALTER DATABASE [Twitter_db] SET  READ_WRITE 
GO
